name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy: 
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        echo "/usr/share/miniconda/bin" >> $GITHUB_PATH

    - name: Check environment.yml
      run: |
        if [ ! -f environment.yml ]; then echo "environment.yml not found"; exit 1; fi

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda install -y flake8 pytest

    - name: Lint with flake8
      run: |
        conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda run -n base pytest
